### ISSUE TITLE
关于标签切换的问题

### ISSUE THREAD

**Issue by lianshi1030** [woai3c/vue-admin-template#1]
以前没写过前端，最近关注了这个项目，发现很简单也很实用。
开始没有修改成cil3的时候，点打开过的标签，进行切换时，之前查询的内容都还在，但是fork到最新的后，也就是cil3后，切换标签后，页面的内容都是最初的空白。我想问问能不能像以前一样，标签切回去后，以前查询的内容依然还在。。。

我大致看了下，发现之前用的都是components下的index.vue，是不是因为都是用的index.vue所以查询过的内容得意保存？

**Comment by woai3c** [comment]
你好 升级到cli3 只是工具升级 对于功能还是一样的 标签内容还是会缓存 可以提供一下更详细的情况吗

**Comment by woai3c** [comment]
对不起 我发现是有这个BUG 非常感谢你的反馈 马上修复

**Comment by woai3c** [comment]
兄弟 BUG 已经修复完了 可以正常使用 原因是每个.vue组件的名字 也就是name属性被我去掉了 补回去就能正常使用

**Comment by woai3c** [comment]
非常感谢你的反馈
