### ISSUE TITLE
如何保证tab在切换的时候 ， 搜索记录仍在？

### ISSUE THREAD

**Issue by dingxihao1991** [woai3c/vue-admin-template#11]
![1572339809(1)](https://user-images.githubusercontent.com/25142979/67752553-2116ce00-fa6e-11e9-95dc-9852fe675bd6.jpg)

**Comment by woai3c** [comment]
你看一下 [demo](https://woai3c.github.io/) 切换 tab 的时候，是不会刷新的，原来的内容保持原样。
文档中也有说明要怎么设置才能在 tab 切换页面时，不清空内容。

> 注意： 组件的名称和路由的名称一定要一致，例如 Home.vue 组件名称 name: home，则在路由文件中也要给它设置为 name: home，否则页面内容不能缓存
```js
// 在router文件中
{
    path: 'home',
    name: 'home',
    component: () => import('../views/Home.vue')
}

// 在Home.vue中
export default {
    name: 'home'
}
```
