### ISSUE TITLE
前后台交互端口问题

### ISSUE THREAD

**Issue by liuyudaniu** [woai3c/vue-admin-template#2]
前台的配置文件没有找到  先做一个代理  与后台不同端口交互

**Comment by woai3c** [comment]
你好 我已经新增了vue.config.js文件 你可以在这里配置跨域代理 具体用法 建议你用搜索引擎或者看官方文档

**Comment by liuyudaniu** [comment]
嗯 我查到了  一般我用vue2  是我无知了

**Comment by lianshi1030** [comment]
感谢这么快就修复了问题，本人前端小白，以后会有很多问题请教
最近在使用你的模板进行扩展，就当帮你测试吧。。
