### ISSUE TITLE
页面跳转到详情页

### ISSUE THREAD

**Issue by youpeixiong** [woai3c/vue-admin-template#21]
请问页面跳转到详情页，路由要怎么配置呢？

**Comment by woai3c** [comment]
如果你是指页面与页面之间跳转的话，可以用 `this.$router.push()` 跳转，参考一下[官方文档](https://router.vuejs.org/zh/api/#router-push)

**Comment by youpeixiong** [comment]
> 如果你是指页面与页面之间跳转的话，可以用 `this.$router.push()` 跳转，参考一下[官方文档](https://router.vuejs.org/zh/api/#router-push)

嗯，不好意思，我的问题描述不清楚。比如我跳转到详情页 this.$router.push( { path: '/goods/detail', } ),  我应该在router/index.js 文件怎么配置路由

**Comment by woai3c** [comment]
```js
export const asyncRoutes = {
    detail: {
        path:  '/goods/detail',
        name: 'detail',
        meta: { title: '主页' },
        component: () => import('../views/detail.vue'),
    },
}
```
这样即可，不过你这种分一二级菜单的可以，可以建立一个一级菜单映射表，一个二级菜单映射表，然后拼在一起。

**Comment by woai3c** [comment]
> > 如果你是指页面与页面之间跳转的话，可以用 `this.$router.push()` 跳转，参考一下[官方文档](https://router.vuejs.org/zh/api/#router-push)
> 
> 嗯，不好意思，我的问题描述不清楚。比如我跳转到详情页 this.$router.push( { path: '/goods/detail', } ), 我应该在router/index.js 文件怎么配置路由

```js
export const asyncRoutes = {
    detail: {
        path:  '/goods/detail',
        name: 'detail',
        meta: { title: '主页' },
        component: () => import('../views/detail.vue'),
    },
}
```
这样即可，不过你这种分一二级菜单的可以，可以建立一个一级菜单映射表，一个二级菜单映射表，然后拼在一起。
