### ISSUE TITLE
权限控制

### ISSUE THREAD

**Issue by zicoolhan** [woai3c/vue-admin-template#22]
这里有实现类似 超级管理员和普通用户的权限控制吗，看了文章然后来看代码，发现并没有这个功能实现诶

**Comment by woai3c** [comment]
这个需要后台实现，例如 admin 用户和 user 用户通过同一个接口获取的菜单数据是不一样的。例如 admin 看到的菜单有 6 个，user 用户看到的是 5 个。前端根据后台返回来的菜单数据来渲染菜单列表。
这就是权限控制，需要前后端相互配合。
