### ISSUE TITLE
开发环境npm run serve可以跨域访问，正式环境打包npm run build后不能跨域访问

### ISSUE THREAD

**Issue by GitHub1527** [woai3c/vue-admin-template#24]
config配置了
publicPath: './',
'/api': {
       target: 'http://127.0.0.1:8083/', 
       *****
}
axios配置访问
 this.$axios.post('/api/testData', {}).
开发环境没错，正式环境前端tomcat8081报错，java后台还是8083端口接口
http://127.0.0.1:8081/api/testData 
Failed to load resource: the server responded with a status of 404 (Not Found)。
访问地址没有代理成http://127.0.0.1:8083/testData
这些参数都加了，想知道这个怎么解决？

**Comment by woai3c** [comment]
如果你打包后的文件是放在服务器根目录下的，就不用加这个。如果不是，就要加这个，这行代码代表相对路径。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"GitHub1527"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月2日(星期二) 上午10:48
收件人:&nbsp;"woai3c/vue-admin-template"<vue-admin-template@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[woai3c/vue-admin-template] 开发环境npm run serve可以跨域访问，正式环境打包npm run build后不能跨域访问 (#24)





 
publicPath: './',这个参数都加了，想知道这个怎么解决？

**Comment by woai3c** [comment]
这只是开发环境的配置，打包后的文件是放在服务器下的。所以接口地址要和服务器地址一致。

**Comment by woai3c** [comment]
> config配置了
> publicPath: './',
> '/api': {
> target: 'http://127.0.0.1:8083/',
> *****
> }
> axios配置访问
> this.$axios.post('/api/testData', {}).
> 开发环境没错，正式环境前端tomcat8081报错，java后台还是8083端口接口
> http://127.0.0.1:8081/api/testData
> Failed to load resource: the server responded with a status of 404 (Not Found)。
> 访问地址没有代理成http://127.0.0.1:8083/testData
> 这些参数都加了，想知道这个怎么解决？

这只是开发环境的配置，打包后的文件是放在服务器下的。所以接口地址要和服务器地址一致。

**Comment by GitHub1527** [comment]
前后端分离打包，java接口地址和前端服务器不一致，有没有配置？有的话告知下，谢谢哈

**Comment by woai3c** [comment]
> 前后端分离打包，java接口地址和前端服务器不一致，有没有配置？有的话告知下，谢谢哈

没有特殊配置，你在前端写的API 地址多少就是多少。你可以创建一个工具函数，生成一个 axios 实例，然后把你后端的接口地址写上去，这样所有的接口都能使用。
