### ISSUE TITLE
Sidebar 组件 内部 嵌套dialog 出现样式异常,  fixed 定位层级嵌套

### ISSUE THREAD

**Issue by Live-forever** [woai3c/vue-admin-template#26]
![image](https://user-images.githubusercontent.com/30582050/84614803-cd240100-aef9-11ea-83e5-87e122453389.png)

![image](https://user-images.githubusercontent.com/30582050/84614823-d9a85980-aef9-11ea-9bca-d6a29a52bb79.png)

**Comment by woai3c** [comment]
兄弟，你是不是发错了。我看你这个像是花裤叉写的。。。 你再确认一下

**Comment by Live-forever** [comment]
用了他的模板呀, 因为 sidebar 组件是fixed 布局,  在这个组件里面 用element-ui  dialog 组件, 就会造成上图这样的样式问题, 我想问一下 作者 有没有什么好一点的解决方案

**Comment by woai3c** [comment]
你可以在 sidebar 再加个 div 改成 relative 布局

**Comment by Live-forever** [comment]
为了不改变原布局, 我直接把这些 dialog 放在App.vue 里了, 然后用vuex 通知App.vue 打开dialog,  这样做是不是 非常不合理 ?

**Comment by woai3c** [comment]
如果你的 dialog 只针对单一页面的话，这样用不太好。否则没什么问题。

**Comment by Live-forever** [comment]
好的，了解！谢谢🙏


| |
陆文祥
|
|
邮箱：18056613516@163.com
|

签名由 网易邮箱大师 定制

在2020年06月17日 16:25，bin 写道：

如果你的 dialog 只针对单一页面的话，这样用不太好。否则没什么问题。

**Comment by woai3c** [comment]
不客气

**Comment by Live-forever** [comment]
有个问题请教下，pinyin这个插件你们支持IE11吗，就是那个search搜索菜单的，我这边试了一下IE11不支持！搞了半天polyfill还是报语法错误！


| |
陆文祥
|
|
邮箱：18056613516@163.com
|

签名由 网易邮箱大师 定制

在2020年06月17日 17:21，bin 写道：

不客气

**Comment by woai3c** [comment]
这你得看 pinyin 插件，我没用过。你可以问一下这个插件的作者。

**Comment by Live-forever** [comment]
好的，谢了


| |
陆文祥
|
|
邮箱：18056613516@163.com
|

签名由 网易邮箱大师 定制

在2020年06月17日 20:06，bin 写道：

这你得看 pinyin 插件，我没用过。你可以问一下这个插件的作者。
