### ISSUE TITLE
跳到一个单独的路由页面，是在哪里设置的？

### ISSUE THREAD

**Issue by Jnskerry** [woai3c/vue-admin-template#28]
text: '单独的路由', // 点击侧边栏跳到一个单独的路由页面，需要提前在 router.js 定义
这个注释说明，我在项目里看了一遍，和其它菜单代码设置都是一样。
不知道这个效果，是要单独设置什么参数？

**Comment by woai3c** [comment]
需要在 router.js 的 commonRoutes 变量里设置，将需要单独展示的页面，设成和 `login` 这种顶级路由一样的等级。
