### ISSUE TITLE
项目后续情况

### ISSUE THREAD

**Issue by susengo** [woai3c/vue-admin-template#3]
非常感谢分享这么好的项目，想请问下后续是否有迭代计划。

**Comment by woai3c** [comment]
目前没有 因为这个项目的目的就是搭好基本的架构 以供他人二次开发使用
当然 我会一直维护 有BUG就会修复

**Comment by woai3c** [comment]
如果你有好的建议 也可以在这反馈 我会适当考虑增加新功能
