### ISSUE TITLE
注销后登录报错

### ISSUE THREAD

**Issue by bingbowan** [woai3c/vue-admin-template#31]
首次登录后访问Index.vue，会设置axios的响应拦截器
注销后，重定向到登录页面，但axios的响应拦截器还有效，后台响应登录返回的结果与首次登录就不一样了
可以考虑注销时也清空掉axios的响应拦截器

**Comment by woai3c** [comment]
感谢反馈，我已经重写 loading 和 axios 的拦截器使用方式了，并提供了一个 demo 放在首页，你可以看一下。
