### ISSUE TITLE
请教一下你用的git message规范和changelog工具

### ISSUE THREAD

**Issue by hellorayza** [woai3c/vue-admin-template#32]
感觉你这个风格挺好的，因为你不是写在脚本里的，就想请教下你怎么做的这两个规范O(∩_∩)O，这两个规范都是用的VS插件还是没写进脚本？update.md是自定义的吗？

**Comment by woai3c** [comment]
[git commit 提交规范](https://github.com/woai3c/Front-end-articles/blob/master/git%20commit%20style.md) git commit 规范在这。

更新日志是自己想的，以前写的很乱，后来迭代了几次就变成现在这样了。

**Comment by hellorayza** [comment]
更新日志不是自动生成的？我以为是用了工具

**Comment by woai3c** [comment]
> 更新日志不是自动生成的？我以为是用了工具

因为更新不频繁，都是手写的。
