### ISSUE TITLE
如何发送ajax请求

### ISSUE THREAD

**Issue by happysmile12321-cocplug** [woai3c/vue-admin-template#37]
比如
import request from '@/utils/request'

export function fetchUserData() {
    return request.get('https://api.github.com/users/woai3c')
}

// test ajax to baidu
export function testAjaxToBaidu() {
    return request.get('http://www.baidu.com')
}
这个test发的请求失败

**Comment by woai3c** [comment]
有些网站是禁止第三方 API 请求的。
