### ISSUE TITLE
左侧边栏的图标怎么设置

### ISSUE THREAD

**Issue by happysmile12321-cocplug** [woai3c/vue-admin-template#40]
menuItems: [
            {
                name: 'home', // 要跳转的路由名称 不是路径
                size: 18, // icon大小
                type: 'md-home', // icon类型
                text: '主页', // 文本内容
            },
类似这个md-home是存在哪里，怎么自定义？

**Comment by woai3c** [comment]
https://www.iviewui.com/components/icon Iview 的 ICON 组件。
