### ISSUE TITLE
项目如何嵌入该项目其他.vue文件

### ISSUE THREAD

**Issue by happysmile12321** [woai3c/vue-admin-template#43]
比如我有一个路由是：
http://localhost:10000/#/flow/flowAnalysis
现在我想嵌入该项目其他.vue文件，http://localhost:10000/#/flow/flowRestriction/ipblock。
这个文件也是在我的项目里面，是另外一个页面。
我试了用iframe嵌入，但是它会将左边栏也嵌入，也就是整个系统嵌入，有没有另外更好的解决方案？

**Comment by woai3c** [comment]
使用 `router-view` 引入组件
