### ISSUE TITLE
还有引用的的css,js，img图片放哪儿呢，作者？？？

### ISSUE THREAD

**Issue by 3xyzq** [woai3c/vue-admin-template#8]

**Comment by woai3c** [comment]
你好，其他资源你可以放在 `assets` 目录。
本项目用的图片都是放在 `assets` 目录的，其他引入的 js 和 css，是引入的依赖。

**Comment by 3xyzq** [comment]
如何配置生产环境呢？






------------------ 原始邮件 ------------------
发件人: "bin"<notifications@github.com>;
发送时间: 2019年7月9日(星期二) 下午3:13
收件人: "woai3c/vue-admin-template"<vue-admin-template@noreply.github.com>;
抄送: "3xyzq"<1778243159@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [woai3c/vue-admin-template] 还有引用的的css,js，img图片放哪儿呢，作者？？？ (#8)




你好，其他资源你可以放在 assets 目录。
 本项目用的图片都是放在 assets 目录的，其他引入的 js 和 css，是引入的依赖。

**Comment by 3xyzq** [comment]
打包发布到服务器访问无法映射  接口报404




------------------ 原始邮件 ------------------
发件人: "bin"<notifications@github.com>;
发送时间: 2019年7月9日(星期二) 下午3:14
收件人: "woai3c/vue-admin-template"<vue-admin-template@noreply.github.com>;
抄送: "3xyzq"<1778243159@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [woai3c/vue-admin-template] 还有引用的的css,js，img图片放哪儿呢，作者？？？ (#8)




Closed #8.
