### ISSUE TITLE
首先感谢作者，对我们新手很友好，然后提几个小问题把

### ISSUE THREAD

**Issue by zhaungsheng** [woai3c/vue-admin-template#9]
刷新记住上一次点击的菜单位置，如果是二级或三级菜单不会展开。这个我不怎么清楚，望作者解答
侧边栏不会根据屏幕大小自动收缩，这个已解决
还有就是觉得iview这个不怎么友好(是真的难用，还是element好用)

**Comment by woai3c** [comment]
你好，反馈的的问题已经修复了。
另外新增了刷新页面默认展开和路由对应的菜单栏这个功能。

**Comment by dingxihao1991** [comment]
我使用了作者这个模板很久了， 今天作者更新了。我该怎么办？

**Comment by zhaungsheng** [comment]
作者都有备注的，自己看一下就知道哪里改了




------------------ 原始邮件 ------------------
发件人: "xihao.ding"<notifications@github.com>;
发送时间: 2019年10月14日(星期一) 下午4:44
收件人: "woai3c/vue-admin-template"<vue-admin-template@noreply.github.com>;
抄送: "947409446"<947409446@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [woai3c/vue-admin-template] 首先感谢作者，对我们新手很友好，然后提几个小问题把 (#9)




我使用了作者这个模板很久了， 今天作者更新了。我该怎么办？

**Comment by dingxihao1991** [comment]
真希望作者能 在gitee 上传一下。guthub 太慢了

**Comment by woai3c** [comment]
> 真希望作者能 在gitee 上传一下。guthub 太慢了

可以看一下我的更新备注和提交的代码，复制粘贴就行，基本上都是小改动，几行代码的事。不会有大影响

**Comment by woai3c** [comment]
> 真希望作者能 在gitee 上传一下。guthub 太慢了

我已经上传到 [gitee](https://gitee.com/woai3c/vue-admin-template) 了，欢迎关注

**Comment by dingxihao1991** [comment]
我刚下载了 最新代码，测试一下，刷新自动展开 还是有点问题，第一次刷新不会展开 第二次刷新会展开

**Comment by woai3c** [comment]
> 刷新记住上一次点击的菜单位置，如果是二级或三级菜单不会展开。这个我不怎么清楚，望作者解答
> 侧边栏不会根据屏幕大小自动收缩，这个已解决
> 还有就是觉得iview这个不怎么友好(是真的难用，还是element好用)

选择 iview 是当时技术选型的问题，如果改用 element 是可以的，不过工作量有点大，还得再开一个仓库重写，等以后有时间再弄吧。

**Comment by woai3c** [comment]
> 我刚下载了 最新代码，测试一下，刷新自动展开 还是有点问题，第一次刷新不会展开 第二次刷新会展开

https://woai3c.github.io/#/password 试试这个网址，我这里测试没问题。你可以加我QQ 411020382。
假如你进入的页面对应是一级菜单，就不会展开菜单栏，只有对应的是二级或三级菜单，才会展开。
